schema_version: 1

context:
  version: 5.1

recipe:
  name: aocl-blas-lapack
  version: ${{ version }}

source:
  - url: https://github.com/amd/blis/archive/refs/tags/${{ version }}.tar.gz
    sha256: 4ab210cea8753f4be9646a3ad8e6b42c7d19380084a66312497c97278b8c76a4
    target_directory: aoclblas
  - url: https://github.com/amd/libflame/archive/refs/tags/${{ version }}.tar.gz
    sha256: 25524ba78b5952303369fa0859d217e44071144fd122a9dc3f72ed0bd73e3b2d
    target_directory: aocllapack
  - url: https://github.com/amd/aocl-utils/archive/refs/tags/${{ version }}.tar.gz
    sha256: 68d75e04013abe90ea8308a9bc99b99532233b6c7f937f35381563f4124c20a5
    target_directory: aoclutils

build:
  number: 0


outputs:
  - package:
      name: aocl-utils
      version: ${{ version }}
    build:
      script: build_aoclutils
      skip:
        - osx
    requirements:
      build:
        - ${{ stdlib("c") }}
        - ${{ compiler("c") }}
        - ${{ compiler("cxx") }}
        - ninja
        - cmake
    tests:
      - script:
          - if: unix
            then:
              - test -f $PREFIX/lib/libaoclutils${SHLIB_EXT}
              - test -f $PREFIX/include/alci/alci.h
          - if: win
            then: 
            - if not exist %LIBRARY_INC%\\alci\\alci.h exit 1
            - if not exist %LIBRARY_BIN%\\libaoclutils.dll exit 1
            - if not exist %LIBRARY_LIB%\\libaoclutils.lib exit 1
  - package:
      name: aocl-blas
      version: ${{ version }}
    build:
      script: build_aoclblas
    requirements:
      build:
        - ${{ stdlib("c") }}
        - ${{ compiler("c") }}
        - ${{ compiler("cxx") }}
        - if: not win
          then: ${{ compiler("fortran") }}
        - if: not linux
          then: llvm-openmp
        - if: linux
          then: libgomp
        - ninja
        - cmake
    tests:
      - script:
          - if: unix
            then: 
              - test -f $PREFIX/lib/libblis-mt${SHLIB_EXT}
              - test -f $PREFIX/include/blis.h
          - if: win
            then:
              - if not exist %LIBRARY_INC%\\blis.h exit 1
              - if not exist %LIBRARY_BIN%\\AOCL-LibBlis-Win-MT-dll.dll exit 1
              - if not exist %LIBRARY_LIB%\\AOCL-LibBlis-Win-MT-dll.lib exit 1
  - package:
      name: aocl-lapack
      version: ${{ version }}
    build:
      script: build_aocllapack
      skip:
        - osx
    requirements:
      build:
        - ${{ stdlib("c") }}
        - ${{ compiler("c") }}
        - ${{ compiler("cxx") }}
        - if: not win
          then: ${{ compiler("fortran") }}
        - if: not linux
          then: llvm-openmp
        - if: linux
          then: libgomp
        - ninja
        - cmake
      host:
        - ${{ pin_subpackage('aocl-utils', exact=True) }}
        - ${{ pin_subpackage('aocl-blas', exact=True) }}
    tests:
      - script:
          - if: unix
            then:
              - test -f $PREFIX/lib/libflame${SHLIB_EXT}
              - test -f $PREFIX/include/lapacke.h
              - test -f $PREFIX/include/libflame.hh
          - if: win
            then:
              - if not exist %LIBRARY_INC%\\libflame.hh exit 1
              - if not exist %LIBRARY_BIN%\\AOCL-LibFlame-Win-MT-dll.dll exit 1
              - if not exist %LIBRARY_LIB%\\AOCL-LibFlame-Win-MT-dll.lib exit 1

about:
  license: BSD-3-Clause
  license_file: LICENSE
  summary: "AMD's fork of BLIS optimized for AMD processors."
  description: |
    AOCL-BLAS is AMD's optimized version of BLAS targeted for AMD EPYC and Ryzen CPUs.
  homepage: https://www.amd.com/en/developer/aocl/dense.html
  repository: https://github.com/amd/blis

extra:
  recipe-maintainers:
    - chillenb
  feedstock-name: aocl-blas
